### ISSUE TITLE
Замечания лаб 1 @paradise900

### ISSUE THREAD

**Issue by ananasn** [paradise900/laba1#1]
@paradise900
Замечания, которые указаны ниже, нужно исправить. Если в остальных работах такое тоже встречается, то исправьте и в них, чтобы мне не повторяться :)

Замечания:
1.  Используйте понятные и описательные имена переменных для данных и фреймов данных. Названия `df, x, ans, ind` и тд не годятся. Это ухудшает читаемость кода.  Например, `df` можно назвать `book_records`.

2.  Для подсчета количества записей лучше использовать инструменты библиотеки pandas раз вы её подключили
```python
books_long_names = books.query('Название.str.len() > 30')
print(f'{len(books_long_names)} - количество записей с длиной более 30')
```
3. Используйте `f`-строки, это самый современный и удобный способ форматирования данных.
```python
# Вместо
print(ans, '- количество записей с длиной более 30')

# Лучше так
print(f'{ans} - количество записей с длиной более 30')

```
4. Используйте символ переноса строки, вместо пустого print
```python
# Вместо
print('Meow ')
print()

# Лучше так
print('Meow\n')
```
5. Не используйте магические числа типа `30,  200, 20` и тд. Создавайте именованные константы, это улучшает читаемость. Например `MIN_NAME_LENGTH = 30`, `MAX_BOOK_PRICE = 200`. константы обычно указываютмя после блока импортов.

6. Не используйте конструкции такого вида `df.iloc[i]['Название']`. Это ухудшает читаемость. Разбейте на две инструкции, это улучшит читаемость, запись будет выглядеть аккуратнее и короче.
```python
# Вместо
ind = [randint(0, df.shape[0]) for _ in range(20)]
for i in ind:
    s = ''
    s += str(df.iloc[i]['Автор']) + ', '
    s += df.iloc[i]['Название'] + ' - '
    s += df.iloc[i]['Дата поступления']
    s += '\n'

#Лучше так
for i in random_indxs:
    book = df.iloc[i]
    autor = book['Автор']
    name = book['Название']
    date = book['Дата поступления']
    link = f'{autor}, {name} - {date}\n'
```

7. По PEP8 все импорты указываются в начале программы. Ознакомьтесь https://peps.python.org/pep-0008/#imports. 
```Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants.
Imports should be grouped in the following order:

Standard library imports.
Related third party imports.
Local application/library specific imports.
```

**Comment by paradise900** [comment]
All the shortcomings have been fixed
